
services:

    jarvis-backend:
      image: ghcr.io/lmor152/jarvis-monorepo/backend:latest
      container_name: jarvis-backend
      restart: unless-stopped
      environment:
        PLEX_URL: ${PLEX_URL}
        PLEX_TOKEN: ${PLEX_TOKEN}
        HA_URL: ${HA_URL}
        HA_TOKEN: ${HA_TOKEN}
        OMNIBOOKER_URL: ${OMNIBOOKER_URL}

    jarvis-assistant:
      image: ghcr.io/lmor152/jarvis-monorepo/assistant:latest
      container_name: jarvis-assistant
      restart: unless-stopped
      environment:
        CHAT_MODEL: ${CHAT_MODEL}
        CHAT_API_KEY: ${OPENAI_API_KEY}
        CHAT_URL: ${CHAT_URL}
        BACKEND_URL: http://jarvis-backend:8000

    # jarvis-frontend:
    #   image: ghcr.io/lmor152/jarvis-monorepo/frontend:latest
    #   container_name: jarvis-frontend
    #   restart: unless-stopped
